class Images {
  static const String intro1 = "assets/images/intro_1.png";
  static const String intro2 = "assets/images/intro_2.png";
  static const String intro3 = "assets/images/intro_3.png";
  static const String logo = "assets/images/logo.png";
  static const String slide = "assets/images/slide.png";
  static const String whatsapp = "assets/images/whatsapp.png";
  static const String telegram = "assets/images/telegram.png";
  static const String viber = "assets/images/viber.png";
  static const String avatar1 = "assets/images/avata-01.jpeg";
  static const String avatar2 = "assets/images/avata-02.jpeg";
  static const String avatar3 = "assets/images/avata-03.jpeg";
  static const String avatar4 = "assets/images/avata-04.png";
  static const String profile1 = "assets/images/profile-1.jpg";
  static const String profile2 = "assets/images/profile-2.jpg";
  static const String profile3 = "assets/images/profile-3.jpg";
  static const String profile4 = "assets/images/profile-4.jpg";
  static const String profile5 = "assets/images/profile-5.jpg";
  static const String profile6 = "assets/images/profile-6.jpg";
  static const String profile7 = "assets/images/profile-7.jpg";
  static const String profile8 = "assets/images/profile-8.jpg";
  static const String trip1 = "assets/images/trip-1.jpg";
  static const String trip2 = "assets/images/trip-2.jpg";
  static const String trip3 = "assets/images/trip-3.jpg";
  static const String trip4 = "assets/images/trip-4.jpg";
  static const String trip5 = "assets/images/trip-5.jpg";
  static const String trip6 = "assets/images/trip-6.jpg";
  static const String trip7 = "assets/images/trip-7.jpg";
  static const String trip8 = "assets/images/trip-8.jpg";
  static const String trip9 = "assets/images/trip-9.jpg";
  static const String room1 = "assets/images/room-1.jpg";
  static const String room2 = "assets/images/room-2.jpg";
  static const String room3 = "assets/images/room-3.jpg";
  static const String room4 = "assets/images/room-4.jpg";
  static const String room5 = "assets/images/room-5.jpg";
  static const String room6 = "assets/images/room-6.jpg";
  static const String room7 = "assets/images/room-7.jpg";
  static const String room8 = "assets/images/room-8.jpg";
  static const String room9 = "assets/images/room-9.jpg";
  static const String room10 = "assets/images/room-10.jpg";
  static const String room11 = "assets/images/room-11.jpg";
  static const String banner1 = "assets/images/banner-1.jpg";
  static const String banner2 = "assets/images/banner-2.jpg";
  static const String banner3 = "assets/images/banner-3.jpg";
  static const String category1 = "assets/images/category-1.jpg";
  static const String category2 = "assets/images/category-2.jpg";
  static const String category3 = "assets/images/category-3.jpg";
  static const String category4 = "assets/images/category-4.jpg";
  static const String gallery1 = "assets/images/gallery-1.jpg";
  static const String gallery2 = "assets/images/gallery-2.jpg";
  static const String location1 = "assets/images/location-1.jpg";
  static const String location2 = "assets/images/location-2.jpg";
  static const String location3 = "assets/images/location-3.jpg";
  static const String location4 = "assets/images/location-4.jpg";
  static const String location5 = "assets/images/location-5.jpg";
  static const String location6 = "assets/images/location-6.jpg";
  static const String location7 = "assets/images/location-7.jpg";
  static const String location8 = "assets/images/location-8.jpg";
  static const String location9 = "assets/images/location-9.jpg";
  static const String location10 = "assets/images/location-10.jpg";
  static const String location11 = "assets/images/location-11.jpg";
  static const String location12 = "assets/images/location-12.jpg";
  static const String location13 = "assets/images/location-13.jpg";
  static const String location14 = "assets/images/location-14.jpg";
  static const String realEstate1 = "assets/images/real-estate-1.jpg";
  static const String realEstate2 = "assets/images/real-estate-2.jpg";
  static const String realEstate3 = "assets/images/real-estate-3.jpg";
  static const String realEstate4 = "assets/images/real-estate-4.jpg";
  static const String realEstate5 = "assets/images/real-estate-5.jpg";
  static const String realEstate6 = "assets/images/real-estate-6.jpg";
  static const String realEstate7 = "assets/images/real-estate-7.jpg";
  static const String realEstate8 = "assets/images/real-estate-8.jpg";
  static const String event1 = "assets/images/event-1.jpg";
  static const String event2 = "assets/images/event-2.jpg";
  static const String event3 = "assets/images/event-3.jpg";
  static const String event4 = "assets/images/event-4.jpg";
  static const String event5 = "assets/images/event-5.jpg";
  static const String event6 = "assets/images/event-6.jpg";
  static const String event7 = "assets/images/event-7.jpg";
  static const String event8 = "assets/images/event-8.jpg";
  static const String event9 = "assets/images/event-9.jpg";
  static const String food1 = "assets/images/food-1.jpg";
  static const String food2 = "assets/images/food-2.jpg";
  static const String food3 = "assets/images/food-3.jpg";
  static const String food4 = "assets/images/food-4.jpg";
  static const String food5 = "assets/images/food-5.jpg";
  static const String food6 = "assets/images/food-6.jpg";
  static const String food7 = "assets/images/food-7.jpg";
  static const String food8 = "assets/images/food-8.jpg";
  static const String place1 = "assets/images/place-1.jpg";
  static const String place2 = "assets/images/place-2.jpg";
  static const String service1 = "assets/images/service-shopping.jpg";
  static const String service2 = "assets/images/service-automotive.jpg";
  static const String service3 = "assets/images/service-coffee.jpg";
  static const String service4 = "assets/images/service-event.jpg";
  static const String service5 = "assets/images/service-housing.jpg";
  static const String service6 = "assets/images/service-job.jpg";
  static const String service7 = "assets/images/service-restaurant.jpg";

  ///Singleton factory
  static final Images _instance = Images._internal();

  factory Images() {
    return _instance;
  }

  Images._internal();
}
